import {createHash} from 'node:crypto';
import {inflateSync} from 'node:zlib';
import {defaultModSettings,validateModSettings,decodeModAttachment,MOD_LIMITS,type ModSettings} from '../../shared/mod-settings';
/** TOML1.0 basic string escaping, including controls that JSON's \u escapes do not cover. */
export function tomlString(value:string):string{let out='"';for(const ch of value){const cp=ch.codePointAt(0)!;out+=ch==='"'?'\\"':ch==='\\'?'\\\\':cp<32||cp===127?`\\u${cp.toString(16).padStart(4,'0')}`:ch;}return out+'"';}
function tomlValue(value:unknown,forceFloat=false):string{if(typeof value==='string')return tomlString(value);if(typeof value==='boolean')return String(value);if(typeof value==='number'&&Number.isFinite(value)){const str=Object.is(value,-0)?'-0':String(value);return forceFloat&&!/[.eE]/.test(str)?str+'.0':str;}if(Array.isArray(value))return `[${value.map(v=>tomlValue(v)).join(', ')}]`;if(value&&typeof value==='object')return `{ ${Object.entries(value).map(([k,v])=>`${tomlString(k)} = ${tomlValue(v,(value as {type?:string}).type==='Number'&&['min','max','step','default'].includes(k))}`).join(', ')} }`;throw Error('Unsupported TOML value.');}
export function renderModToml(value:ModSettings):string{const mod=validateModSettings(value),{config_options,native_libraries,...manifest}=mod.manifest;let out='[manifest]\n'+Object.entries({...manifest,native_libraries,config_options}).map(([k,v])=>`${k} = ${tomlValue(v)}`).join('\n');out+='\n\n[inputs]\n'+Object.entries(mod.inputs).map(([k,v])=>`${k} = ${tomlValue(v)}`).join('\n');return out+'\n';}
function crc32(bytes:Uint8Array){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let n=0;n<8;n++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
/** Icons imported by Electron are normalized8-bit RGB/RGBA PNGs, never arbitrary image executables. */
export function validateProjectIcon(bytes:Uint8Array):void{
  if(bytes.length>MOD_LIMITS.iconBytes||bytes.length<45||Buffer.from(bytes.subarray(0,8)).toString('hex')!=='89504e470d0a1a0a')throw Error('Icon must be a bounded normalized PNG.');const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.length),idat:Uint8Array[]=[];let at=8,width=0,height=0,bpp=0,ended=false,idatEnded=false;
  while(at<bytes.length){if(at+12>bytes.length)throw Error('Truncated PNG chunk.');const size=view.getUint32(at);if(size>MOD_LIMITS.iconBytes||at+size+12>bytes.length)throw Error('PNG chunk exceeds icon bounds.');const type=Buffer.from(bytes.subarray(at+4,at+8)).toString('latin1');if(crc32(bytes.subarray(at+4,at+8+size))!==view.getUint32(at+8+size))throw Error('PNG checksum mismatch.');
    if(!/^[A-Za-z]{4}$/.test(type)||type[0]===type[0].toUpperCase()&&!['IHDR','IDAT','IEND','PLTE'].includes(type))throw Error('Unsupported PNG critical chunk.');if(type==='PLTE'&&(idat.length||!size||size>768||size%3))throw Error('Invalid PNG palette.');if(idat.length&&type!=='IDAT')idatEnded=true;if(type==='IDAT'&&idatEnded)throw Error('PNG IDAT chunks must be contiguous.');
    if(at===8){if(type!=='IHDR'||size!==13)throw Error('PNG needs a valid first IHDR.');width=view.getUint32(at+8);height=view.getUint32(at+12);bpp=bytes[at+17]===6?4:bytes[at+17]===2?3:0;if(!width||!height||width*height>MOD_LIMITS.iconPixels||bytes[at+16]!==8||!bpp||bytes[at+18]||bytes[at+19]||bytes[at+20])throw Error('Icon must be normalized8-bit RGB/RGBA PNG, noninterlaced, at most1M pixels.');}
    else if(type==='IHDR')throw Error('Duplicate PNG header.');if(type==='IDAT')idat.push(bytes.subarray(at+8,at+8+size));if(type==='IEND'){if(size||at+12!==bytes.length)throw Error('Invalid PNG end.');ended=true;break;}at+=size+12;
  }
  if(!ended||!idat.length)throw Error('PNG image data or end is absent.');const expected=(width*bpp+1)*height,raw=inflateSync(Buffer.concat(idat),{maxOutputLength:expected});if(raw.length!==expected)throw Error('PNG decoded byte count differs from dimensions.');for(let row=0;row<height;row++)if(raw[row*(width*bpp+1)]>4)throw Error('Invalid PNG filter.');
}
export function validateModAttachmentBytes(mod:ModSettings):void{for(const a of [...mod.attachments,...(mod.icon?[mod.icon]:[])]){const bytes=decodeModAttachment(a);if(createHash('sha256').update(bytes).digest('hex')!==a.sha256)throw Error(`Attachment ${a.name} SHA256 mismatch.`);if(a===mod.icon)validateProjectIcon(bytes);}}
export {defaultSymbolKind} from '../../shared/mod-settings';
export function modExportFiles(project:{id:string;name:string;mod?:ModSettings},forBuild=false){
  const settings=validateModSettings(project.mod??defaultModSettings(project));validateModAttachmentBytes(settings);if(forBuild&&settings.manifest.game_id!=='mnsg')throw Error('This generated native patch targets MNSG; set manifest.game_id to mnsg before building.');
  const binaryFiles:Record<string,Uint8Array>={},nativeLibraryFiles:Record<string,Uint8Array>={},warnings:string[]=[];for(const a of [...settings.attachments,...(settings.icon?[settings.icon]:[])])binaryFiles[a.name]=decodeModAttachment(a);
  for(const lib of settings.manifest.native_libraries){const matches=settings.attachments.filter(a=>{const basename=a.name.split('/').at(-1)!;return ['.dll','.dylib','.so'].some(ext=>basename===lib.name+ext);});if(!matches.length)warnings.push(`Native library ${lib.name} has no uploaded platform sidecar. The game loads native libraries beside the NRM, not from inside it.`);for(const a of matches){const basename=a.name.split('/').at(-1)!;if(nativeLibraryFiles[basename])throw Error(`Duplicate native library sidecar ${basename}.`);nativeLibraryFiles[basename]=binaryFiles[a.name];}}
  if(settings.manifest.custom_gamemode)warnings.push('custom_gamemode is packaged but ignored by the currently supported Goemon runtime.');if(settings.manifest.config_options.length)warnings.push('Config options create the game mod-menu schema; generated room patches do not automatically consume these values.');if(Object.keys(nativeLibraryFiles).length)warnings.push('Native library sidecars are copied beside the NRM. Filename matching does not verify architecture or native ABI compatibility.');
  return {settings,modId:settings.manifest.id,fileName:settings.inputs.mod_filename+'.nrm',toml:renderModToml(settings),binaryFiles,nativeLibraryFiles,warnings};
}
