// Verified room names from mnsg-documentation/data/values-rooms.json.
export const ROOM_NAMES: Record<number, string> = {
  "0": "Oedo Castle (specific room name unknown)",
  "2": "Oedo Castle (specific room name unknown)",
  "3": "Oedo Castle (specific room name unknown)",
  "4": "Oedo Castle (specific room name unknown)",
  "5": "Oedo Castle (specific room name unknown)",
  "6": "Oedo Castle (specific room name unknown)",
  "7": "Oedo Castle (specific room name unknown)",
  "8": "Oedo Castle (specific room name unknown)",
  "9": "Oedo Castle (specific room name unknown)",
  "10": "Oedo Castle (specific room name unknown)",
  "11": "Oedo Castle (specific room name unknown)",
  "12": "Oedo Castle (specific room name unknown)",
  "13": "Oedo Castle (specific room name unknown)",
  "14": "Oedo Castle (specific room name unknown)",
  "15": "Oedo Castle (specific room name unknown)",
  "16": "Oedo Castle (specific room name unknown)",
  "17": "Oedo Castle (specific room name unknown)",
  "18": "Oedo Castle (specific room name unknown)",
  "20": "Oedo Castle (specific room name unknown)",
  "21": "Oedo Castle (specific room name unknown)",
  "22": "Oedo Castle \u2014 Congo battle",
  "26": "Oedo Castle \u2014 approach before Congo battle",
  "40": "Oedo Castle (specific room name unknown)",
  "47": "Ghost Toys Castle (specific room name unknown)",
  "48": "Ghost Toys Castle (specific room name unknown)",
  "49": "Ghost Toys Castle (specific room name unknown)",
  "50": "Ghost Toys Castle (specific room name unknown)",
  "51": "Ghost Toys Castle (specific room name unknown)",
  "52": "Ghost Toys Castle (specific room name unknown)",
  "53": "Ghost Toys Castle (specific room name unknown)",
  "54": "Ghost Toys Castle (specific room name unknown)",
  "57": "Ghost Toys Castle (specific room name unknown)",
  "58": "Ghost Toys Castle (specific room name unknown)",
  "59": "Ghost Toys Castle (specific room name unknown)",
  "60": "Ghost Toys Castle (specific room name unknown)",
  "62": "Ghost Toys Castle (specific room name unknown)",
  "63": "Ghost Toys Castle (specific room name unknown)",
  "64": "Ghost Toys Castle (specific room name unknown)",
  "65": "Ghost Toys Castle (specific room name unknown)",
  "66": "Ghost Toys Castle (specific room name unknown)",
  "67": "Ghost Toys Castle (specific room name unknown)",
  "68": "Ghost Toys Castle (specific room name unknown)",
  "69": "Ghost Toys Castle (specific room name unknown)",
  "70": "Ghost Toys Castle (specific room name unknown)",
  "73": "Ghost Toys Castle \u2014 Dharumanyo battle",
  "90": "Festival Temple Castle (specific room name unknown)",
  "91": "Festival Temple Castle (specific room name unknown)",
  "92": "Festival Temple Castle (specific room name unknown)",
  "93": "Festival Temple Castle (specific room name unknown)",
  "94": "Festival Temple Castle (specific room name unknown)",
  "95": "Festival Temple Castle (specific room name unknown)",
  "96": "Festival Temple Castle (specific room name unknown)",
  "97": "Festival Temple Castle (specific room name unknown)",
  "98": "Festival Temple Castle (specific room name unknown)",
  "99": "Festival Temple Castle (specific room name unknown)",
  "100": "Festival Temple Castle (specific room name unknown)",
  "101": "Festival Temple Castle (specific room name unknown)",
  "102": "Festival Temple Castle (specific room name unknown)",
  "103": "Festival Temple Castle (specific room name unknown)",
  "104": "Festival Temple Castle (specific room name unknown)",
  "105": "Festival Temple Castle (specific room name unknown)",
  "106": "Festival Temple Castle (specific room name unknown)",
  "107": "Festival Temple Castle (specific room name unknown)",
  "108": "Festival Temple Castle (specific room name unknown)",
  "109": "Festival Temple Castle (specific room name unknown)",
  "110": "Festival Temple Castle (specific room name unknown)",
  "111": "Festival Temple Castle (specific room name unknown)",
  "112": "Festival Temple Castle (specific room name unknown)",
  "113": "Festival Temple Castle \u2014 Tsurami battle",
  "129": "Gourmet Submarine (specific room name unknown)",
  "130": "Gourmet Submarine (specific room name unknown)",
  "131": "Gourmet Submarine (specific room name unknown)",
  "133": "Gourmet Submarine (specific room name unknown)",
  "134": "Gourmet Submarine (specific room name unknown)",
  "135": "Gourmet Submarine (specific room name unknown)",
  "137": "Gourmet Submarine (specific room name unknown)",
  "138": "Gourmet Submarine (specific room name unknown)",
  "139": "Gourmet Submarine (specific room name unknown)",
  "140": "Gourmet Submarine (specific room name unknown)",
  "141": "Gourmet Submarine (specific room name unknown)",
  "142": "Gourmet Submarine (specific room name unknown)",
  "144": "Gourmet Submarine (specific room name unknown)",
  "145": "Gourmet Submarine (specific room name unknown)",
  "148": "Gourmet Submarine (specific room name unknown)",
  "149": "Gourmet Submarine (specific room name unknown)",
  "150": "Gourmet Submarine (specific room name unknown)",
  "151": "Gourmet Submarine (specific room name unknown)",
  "152": "Gourmet Submarine (specific room name unknown)",
  "153": "Gourmet Submarine (specific room name unknown)",
  "157": "Gourmet Submarine (specific room name unknown)",
  "168": "Gorgeous Music Castle (specific room name unknown)",
  "169": "Gorgeous Music Castle (specific room name unknown)",
  "170": "Gorgeous Music Castle (specific room name unknown)",
  "171": "Gorgeous Music Castle (specific room name unknown)",
  "172": "Gorgeous Music Castle (specific room name unknown)",
  "173": "Gorgeous Music Castle (specific room name unknown)",
  "174": "Gorgeous Music Castle (specific room name unknown)",
  "175": "Gorgeous Music Castle (specific room name unknown)",
  "176": "Gorgeous Music Castle (specific room name unknown)",
  "177": "Gorgeous Music Castle (specific room name unknown)",
  "178": "Gorgeous Music Castle (specific room name unknown)",
  "179": "Gorgeous Music Castle (specific room name unknown)",
  "180": "Gorgeous Music Castle (specific room name unknown)",
  "181": "Gorgeous Music Castle (specific room name unknown)",
  "182": "Gorgeous Music Castle (specific room name unknown)",
  "183": "Gorgeous Music Castle (specific room name unknown)",
  "184": "Gorgeous Music Castle (specific room name unknown)",
  "185": "Gorgeous Music Castle (specific room name unknown)",
  "186": "Gorgeous Music Castle (specific room name unknown)",
  "187": "Gorgeous Music Castle (specific room name unknown)",
  "188": "Gorgeous Music Castle (specific room name unknown)",
  "189": "Gorgeous Music Castle (specific room name unknown)",
  "190": "Gorgeous Music Castle (specific room name unknown)",
  "191": "Gorgeous Music Castle (specific room name unknown)",
  "192": "Gorgeous Music Castle (specific room name unknown)",
  "193": "Gorgeous Music Castle (specific room name unknown)",
  "300": "Kai Highway",
  "301": "Mt. Fuji (bottom)",
  "302": "Mt. Fuji crater",
  "303": "Mt. Fuji (peak)",
  "304": "Musashi Beach",
  "305": "Musashi Tunnel",
  "306": "Iga",
  "307": "Yamato Shrine Exterior",
  "308": "Yamato Shrine Interior",
  "309": "Yamato (specific room name unknown)",
  "310": "Yamato Bamboo Forest",
  "311": "Turtle Stone",
  "312": "Kii Awaji Island",
  "313": "Husband and Wife Rocks",
  "314": "Tosa Fields",
  "315": "Tosa Bridge",
  "316": "Kompira Mountain First Block",
  "317": "Kompira Mountain Second Block",
  "318": "Kompira Mountain Third Block",
  "319": "Kompira Mountain Fourth Block",
  "320": "Kompira Mountain Grounds",
  "321": "Iyo Hills",
  "322": "Dogo Hotsprings",
  "323": "Kurashiki",
  "324": "Nagato",
  "325": "Hagi",
  "326": "Akiyoshidai",
  "327": "Shuhodo",
  "328": "Izumo",
  "329": "Lake with a Large Tree",
  "330": "Inaba Dune",
  "331": "Mt. Fear",
  "332": "Ugo Stone Circle",
  "333": "Shoreline",
  "334": "Underwater Japan Sea",
  "335": "Tunnel to Northeast 1",
  "336": "Tunnel to Northeast 2",
  "337": "Mutsu Crossroads",
  "338": "Uzen Tunnel",
  "339": "Gateway Viewpoint",
  "340": "Waterfall of Kegon",
  "341": "Koryuta's flight \u2014 airborne Control Machine encounter",
  "343": "Mermaid Waterfall (marked unused)",
  "350": "Oedo Town Super Pass Bridge",
  "351": "Oedo Town Shopping District",
  "352": "Oedo Town Shrine Area",
  "353": "Oedo Town Housing",
  "354": "Oedo Town Nihon Bashi Bridge",
  "355": "Oedo Town Outside Kai Highway",
  "356": "Oedo Castle Main Gate",
  "357": "Stairs to Oedo Castle",
  "358": "Oedo Castle Entrance",
  "359": "Zazen Town Entrance",
  "360": "Zazen Town Bridge",
  "361": "Zazen Town Main Town",
  "362": "Zazen Town Watering Hole",
  "363": "Zazen Town Duck Creek Jump Area",
  "364": "Zazen Town Back",
  "365": "Zazen Town Golden Temple",
  "366": "Zazen Town Bizen Bridge",
  "367": "Zazen Town \u2014 Mt. Nyoigatake sidewalk",
  "368": "Zazen Town \u2014 Mt. Nyoigatake fire shrine",
  "369": "Zazen Town \u2014 Benkei Bridge",
  "370": "Zazen Town Duck Creek Upstream",
  "371": "Zazen Town Duck Creek Ushiwaka",
  "373": "Folkypoke Village Hay Farm",
  "374": "Folkypoke Village Housing",
  "375": "Folkypoke Village Shopping District",
  "376": "Folkypoke Village Entrance",
  "377": "Festival Village Entrance",
  "378": "Festival Village Shopping District",
  "379": "Festival Village Stage",
  "380": "Festival Village Rear",
  "381": "Festival Village (specific room name unknown)",
  "433": "Kai Coffee Shop",
  "435": "Kii Coffee Shop",
  "436": "Kompira Coffee Shop",
  "437": "Iyo Coffee Shop",
  "438": "Izumo Coffee Shop",
  "440": "Oedo Tourist Center \u2014 Awa branch",
  "441": "Oedo Tourist Center \u2014 Awaji Island branch",
  "464": "Sasuke Jetpack Training",
  "465": "Goemon's House",
  "466": "Mt. Fuji salesman room",
  "480": "Goemon Impact Minigame",
  "481": "Ebisumaru Sweets Minigame",
  "482": "Sasuke High Jump Minigame",
  "550": "World Map",
  "608": "Impact boss rush \u2014 Kashiwagi",
  "609": "Impact boss rush \u2014 Taisamba 2",
  "610": "Impact boss rush \u2014 Balberra",
  "611": "Impact boss rush \u2014 D'Etoile"
};
